apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
      manifests:
        - ./infra/k8s/*
        - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: lfalmeida/auth 
      context: auth 
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: lfalmeida/client
      context: client 
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: lfalmeida/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .            
    - image: lfalmeida/orders
      context: orders
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .            
    - image: lfalmeida/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .            
    - image: lfalmeida/payments
      context: payments
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .